app.mode=predict
input.path=data/input
intermediate.path=data/output
output.path=data/features
checkpoint.path=data/checkpoint-consumer
model.path=models/model.pkl
batch.size=20
stream.interval=5
image.width=224
image.height=224
